image: docker.slock.it/build-images/node:8-alpine
variables:
  COMMIT_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - test
  - package
  - deploy

build-server:
  stage: build
  tags:
    - short-jobs
  script:
    - sh /prepare.sh
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules/
      - js/

compile-contracts:
  stage: build
  tags:
    - short-jobs
  services:
    - docker:dind
  image: jonaskello/docker-and-compose:latest
  script:
    - docker run -v $(pwd)/contracts:/contracts ethereum/solc:0.5.7 --optimize --combined-json abi,bin,bin-runtime,compact-format,hashes,interface,metadata /contracts/ServerRegistry.sol /contracts/ChainRegistry.sol /contracts/BlockhashRegistry.sol > contracts/contracts.json; docker run -v $(pwd)/test:/test ethereum/solc:0.4.25 --optimize --combined-json abi,bin,bin-runtime,compact-format,hashes,interface,metadata /test/contracts/TestContract.sol > test/contracts/contracts.json
  artifacts:
    paths:
      - contracts/contracts.json

test-parity:
  stage: test
  tags:
    - short-jobs
  variables:
    RPCURL: http://parity:8545
    IPFS_URL: http://ipfs:5001
  services:
    - name: jbenet/go-ipfs:latest
      command:
        - daemon
        - --offline
      alias: ipfs
    - name: docker.slock.it/core-technology/parity-timemachine:master
      command:
        - --jsonrpc-experimental
        - --jsonrpc-apis=all
        - --logging=3
        - --jsonrpc-interface=all
        - --ws-interface=all
        - --chain=dev
        - --gas-cap=8000000
        - --gasprice=0
        - --reseal-min-period=0
        - --gas-floor-target=8700000
        - --tracing=on
      alias: parity
  script:
    - sh /prepare.sh
    - npm install
    - npm run testCoverage
  dependencies:
    - build-server
    - compile-contracts
  artifacts:
    name: "test-reports-$CI_JOB_NAME"
    paths:
      - test/report

test-geth:
  stage: test
  tags:
    - short-jobs
  variables:
    RPCURL: http://geth:8545
    IPFS_URL: http://ipfs:5001
  services:
    - name: jbenet/go-ipfs:latest
      command:
        - daemon
        - --offline
      alias: ipfs
    - name: docker.slock.it/build-images/geth:v1.8.18
      alias: geth
  script:
    - sh /prepare.sh
    - npm install
  #        - npm run testCoverage             just for now geth seems to have some issues
  dependencies:
    - build-server
    - compile-contracts
  artifacts:
    name: "test-reports-$CI_JOB_NAME"
    paths:
      - test/report

pages:
  stage: deploy
  tags:
    - short-jobs
  environment:
    name: test-results
    url: http://in3.git-pages.slock.it/in3-server
  dependencies:
    - test-parity
    - test-geth
  script:
    - mkdir -p public/
    - cp -r test/report/* public/
  artifacts:
    paths:
      - public

package-docker:
  stage: package
  tags:
    - short-jobs
  services:
    - docker:dind
  image: jonaskello/docker-and-compose:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --build-arg NPM_REGISTRY_TOKEN=${NPM_REGISTRY_TOKEN} -t $COMMIT_IMAGE_TAG .
    - docker tag $COMMIT_IMAGE_TAG $RELEASE_IMAGE_TAG
    - docker push $RELEASE_IMAGE_TAG
    - docker push $COMMIT_IMAGE_TAG

deploy-to-dev:
  stage: deploy
  tags:
    - long-jobs
  only:
    - master
    - develop
  image: markuskeil/docker-and-rancher
  services:
    - docker:dind
  script:
    - rancher -w up -d --prune -p -s $CI_PROJECT_PATH_SLUG -c --force-upgrade
