version: '2'
services:
  lb-monitor:
    scale: 1
    start_on_create: true
  nd-1:
    scale: 1
    start_on_create: true
    
  nd-2:
    scale: 1
    start_on_create: true
    
  nd-3:
    scale: 1
    start_on_create: true
    
  nd-4:
    scale: 1
    start_on_create: true
    
  nd-5:
    scale: 1
    start_on_create: true

  lb:
    start_on_create: true
    lb_config:
      certs: []
      config: "listen stats \nbind 0.0.0.0:9000\nmode http\nstats enable\nstats hide-version\n\
        stats realm Haproxy\\ Statistics\nstats uri /haproxy_stats"
      port_rules:
      - hostname: ''
        path: /${CHAIN}/nd-1
        priority: 2
        protocol: http
        service: nd-1
        source_port: 80
        target_port: 8500
      - hostname: ''
        path: /${CHAIN}/nd-2
        priority: 2
        protocol: http
        service: nd-2
        source_port: 80
        target_port: 8500
      - hostname: ''
        path: /${CHAIN}/nd-3
        priority: 2
        protocol: http
        service: nd-3
        source_port: 80
        target_port: 8500
      - hostname: ''
        path: /${CHAIN}/nd-4
        priority: 2
        protocol: http
        service: nd-4
        source_port: 80
        target_port: 8500
      - hostname: ''
        path: /${CHAIN}/nd-5
        priority: 2
        protocol: http
        service: nd-5
        source_port: 80
        target_port: 8500

    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
